### ISSUE TITLE
Tip, for future plugin promo

### ISSUE THREAD

**Issue by yazonnile** [Vehmloewff/rollup-plugin-glob-files#2]
Hi, @Vehmloewff 
Thanks for the awesome plugin!

I've found it just accidental, and I was looking for something similar to Webpack `require.context` or `require.ensure`, but for Rollup.

And this plugin is an answer. All I want to tell you - please add to description/readme something like this: 
> My plugin works similar to `webpack` `require.context` or `require.ensure`, but for `rollup`, enjoy

It helps to someone like me in a future to find this great plugin

Thanks again. Good luck.

**Comment by Vehmloewff** [comment]
Thanks for pointing that out.  I just added a line similar to the one you suggested in commit 1e3d898584afe257f3a37b51925af5f6f80cf137.

I am very glad you find this plugin useful!
